In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings 
warnings.filterwarnings('ignore')

In [2]:
train_data=pd.read_csv(r'C:\Users\LENOVO\Downloads\cars_train.csv',header=None)
print(train_data.head())
test_data=pd.read_csv(r'C:\Users\LENOVO\Downloads\cars_test.csv',header=None)
print(test_data.head())

       0      1      2     3      4    5      6
0  vhigh   high      3  more  small  low  unacc
1    low  vhigh      3     4  small  med  unacc
2    low   high  5more  more    big  low  unacc
3   high    med      4     2  small  med  unacc
4    low    low      3  more    big  med   good
       0      1      2     3      4     5      6
0    med  vhigh  5more     4  small   low  unacc
1  vhigh   high      2     2    big   med  unacc
2    low   high      2  more  small   low  unacc
3  vhigh  vhigh      3     2    big  high  unacc
4    low    med      4     4    med   med   good


In [3]:
print(train_data.shape)
print(test_data.shape)

(1382, 7)
(346, 7)


In [4]:
train_data.columns=['BUYING','MAINT','DOORS','PERSONS','LUG_BOOT','SAFETY','CLASESS']
test_data.columns=['BUYING','MAINT','DOORS','PERSONS','LUG_BOOT','SAFETY','CLASESS']

In [5]:
train_data.head()

BUYING  MAINT  DOORS PERSONS LUG_BOOT SAFETY CLASESS
0  vhigh   high      3    more    small    low   unacc
1    low  vhigh      3       4    small    med   unacc
2    low   high  5more    more      big    low   unacc
3   high    med      4       2    small    med   unacc
4    low    low      3    more      big    med    good

In [6]:
test_data.head()

BUYING  MAINT  DOORS PERSONS LUG_BOOT SAFETY CLASESS
0    med  vhigh  5more       4    small    low   unacc
1  vhigh   high      2       2      big    med   unacc
2    low   high      2    more    small    low   unacc
3  vhigh  vhigh      3       2      big   high   unacc
4    low    med      4       4      med    med    good

In [7]:
test_data.drop('CLASESS',axis=1,inplace=True)
test_data.head()

BUYING  MAINT  DOORS PERSONS LUG_BOOT SAFETY
0    med  vhigh  5more       4    small    low
1  vhigh   high      2       2      big    med
2    low   high      2    more    small    low
3  vhigh  vhigh      3       2      big   high
4    low    med      4       4      med    med

In [8]:
colname=[]
for x in train_data.columns:
    if train_data[x].dtype=='object':
        colname.append(x)
colname

['BUYING', 'MAINT', 'DOORS', 'PERSONS', 'LUG_BOOT', 'SAFETY', 'CLASESS']

In [9]:
#for preprocessing the data
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

for x in colname:
    train_data[x]=le.fit_transform(train_data[x])

    le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print('Feature', x)
    print('mapping', le_name_mapping)
    

Feature BUYING
mapping {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
Feature MAINT
mapping {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
Feature DOORS
mapping {'2': 0, '3': 1, '4': 2, '5more': 3}
Feature PERSONS
mapping {'2': 0, '4': 1, 'more': 2}
Feature LUG_BOOT
mapping {'big': 0, 'med': 1, 'small': 2}
Feature SAFETY
mapping {'high': 0, 'low': 1, 'med': 2}
Feature CLASESS
mapping {'acc': 0, 'good': 1, 'unacc': 2, 'vgood': 3}


In [10]:
colname=[]
for x in test_data.columns:
    if test_data[x].dtype=='object':
        colname.append(x)
colname

['BUYING', 'MAINT', 'DOORS', 'PERSONS', 'LUG_BOOT', 'SAFETY']

In [11]:
#for preprocessing the data
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

for x in colname:
    test_data[x]=le.fit_transform(test_data[x])

    le_name_mapping = dict(zip(le.classes_, le.transform(le.classes_)))
    print('Feature', x)
    print('mapping', le_name_mapping)
    

Feature BUYING
mapping {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
Feature MAINT
mapping {'high': 0, 'low': 1, 'med': 2, 'vhigh': 3}
Feature DOORS
mapping {'2': 0, '3': 1, '4': 2, '5more': 3}
Feature PERSONS
mapping {'2': 0, '4': 1, 'more': 2}
Feature LUG_BOOT
mapping {'big': 0, 'med': 1, 'small': 2}
Feature SAFETY
mapping {'high': 0, 'low': 1, 'med': 2}


In [12]:
train_data.head()

####0--->acc
###1--->good
###2-->unacc
####3-->vgood

BUYING  MAINT  DOORS  PERSONS  LUG_BOOT  SAFETY  CLASESS
0       3      0      1        2         2       1        2
1       1      3      1        1         2       2        2
2       1      0      3        2         0       1        2
3       0      2      2        0         2       2        2
4       1      1      1        2         0       2        1

In [13]:
test_data.head()

BUYING  MAINT  DOORS  PERSONS  LUG_BOOT  SAFETY
0       2      3      3        1         2       1
1       3      0      0        0         0       2
2       1      0      0        2         2       1
3       3      3      1        0         0       0
4       1      2      2        1         1       2

In [14]:
x=train_data.values[:,0:-1]
y=train_data.values[:,-1]

In [15]:
x.shape

(1382, 6)

In [16]:
y.shape

(1382,)

In [17]:
from sklearn.preprocessing import StandardScaler
scaler= StandardScaler()
scaler.fit(x)
x=scaler.transform(x)

In [18]:
print(x)

[[ 1.33507272 -1.3488262  -0.45682233  1.21505861  1.22565305  0.00176987]
 [-0.44760409  1.32688358 -0.45682233 -0.01064285  1.22565305  1.22474807]
 [-0.44760409 -1.3488262   1.33418038  1.21505861 -1.21505663  0.00176987]
 ...
 [-1.33894249  1.32688358  1.33418038 -0.01064285  0.00529821 -1.22120833]
 [ 0.44373431  0.43498032  0.43867903 -0.01064285 -1.21505663  0.00176987]
 [ 0.44373431 -0.45692294  1.33418038  1.21505861  1.22565305 -1.22120833]]


In [19]:
from sklearn.model_selection import train_test_split

#split the data into  the test and train
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=10)

## test_size is 20%  for less than 1000 obsevation and greater than 1000 30%

In [20]:
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(1105, 6)
(1105,)
(277, 6)
(277,)


# RUNNING A DECISION TREE

In [21]:
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(criterion='gini',random_state=10,)

#fit the model on data and predict the values

model_DecisionTree.fit(x_train,y_train)

y_pred=model_DecisionTree.predict(x_test)

#print(y_pred)
print(list(zip(y_test,y_pred)))

[(2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (1, 1), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (1, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (3, 3), (0, 0), (2, 2), (0, 0), (3, 3), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (1, 0), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (0, 0), (3, 3), (0, 0), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (3, 3), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (3, 3), (2, 2), (0, 0), (3, 3), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (3, 3), (2, 2), (0, 0), (2, 2), (0, 0),

In [22]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ',)
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[ 69   1   1   0]
 [  4   8   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
classification report: 
              precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       0.89      0.67      0.76        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.91      0.93       277
weighted avg       0.98      0.98      0.98       277

accuracy of the model:  0.9783393501805054


# FOR CHECKING THE SCORE

In [23]:
model_DecisionTree.score(x_train,y_train)

1.0

# FOR FEATURE SELECTION OR VARIABLE SELECTION CAN BE CHECKED IN ALL ALGORITHMS

In [24]:
print(list(zip(train_data.columns[0:-1],model_DecisionTree.feature_importances_)))

[('BUYING', 0.21976792783843332), ('MAINT', 0.18220929667385857), ('DOORS', 0.062005934167191426), ('PERSONS', 0.19425872158174767), ('LUG_BOOT', 0.09772725134941933), ('SAFETY', 0.24403086838934968)]


In [25]:
train_data.columns[:-1]

Index(['BUYING', 'MAINT', 'DOORS', 'PERSONS', 'LUG_BOOT', 'SAFETY'], dtype='object')

In [26]:
from sklearn import tree
with open(r"model_DecisionTree.txt", "w") as f:
    
    f = tree.export_graphviz(model_DecisionTree, feature_names=train_data.columns[0:-1],
                             out_file=f)
    
#generate the file and upload the code in webgraphviz.com to plot the decision tree

# PERFORMING SVC ON SAME DATA

In [27]:
from sklearn.svm import SVC
#create a model
svc_model=SVC(kernel='rbf',C=90,gamma=0.1)
#fitting training data into the model
svc_model.fit(x_train,y_train)
y_pred=svc_model.predict(x_test)
print(y_pred)
print(list(zip(y_test,y_pred)))

[2 2 2 2 2 2 0 2 2 1 0 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 0 2 0 1 2 2 2 0 2
 2 0 2 2 2 2 2 3 0 2 0 3 0 2 0 2 2 2 2 2 2 0 2 0 2 2 0 2 2 1 2 0 0 2 2 0 3
 0 0 2 2 0 2 0 2 2 0 2 2 0 2 2 2 0 2 2 0 2 2 2 2 2 0 3 2 2 0 0 2 2 2 0 2 0
 3 2 0 3 2 2 2 2 2 3 2 0 2 0 2 2 0 2 2 2 2 0 2 2 2 2 0 2 2 2 0 2 2 2 0 0 2
 2 2 2 2 0 2 2 0 2 2 2 2 2 2 1 2 2 2 3 0 0 2 2 0 2 2 2 2 2 0 2 0 0 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 1 0 2 2 2 2 2 0 0 2 3 1 2 2 0 0 2 0 0
 0 2 2 0 2 2 2 2 0 0 0 2 2 2 0 2 0 2 0 0 0 1 1 2 2 2 0 2 2 2 2 0 1 2 2 2 2
 2 0 2 2 2 2 2 0 2 2 0 0 2 2 1 2 2 2]
[(2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (1, 1), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (1, 1), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (3, 3), (0, 0), (2, 2), (0, 0), (3, 3), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 

In [28]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ',)
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[ 69   0   2   0]
 [  2  10   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
classification report: 
              precision    recall  f1-score   support

           0       0.97      0.97      0.97        71
           1       1.00      0.83      0.91        12
           2       0.99      1.00      0.99       185
           3       1.00      1.00      1.00         9

    accuracy                           0.99       277
   macro avg       0.99      0.95      0.97       277
weighted avg       0.99      0.99      0.99       277

accuracy of the model:  0.9855595667870036


In [29]:
svc_model.score(x_train,y_train)

1.0

# KNN

In [30]:
##predicting using the KNeighbors_classifier
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=6,
                               metric='euclidean')

#euclidean,manhattan,min kowski
#fit the model in the data and predict the values

model_KNN.fit(x_train,y_train)
y_pred=model_KNN.predict(x_test)
print(list(zip(y_test,y_pred)))

[(2, 2), (2, 2), (2, 2), (2, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (1, 1), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (1, 0), (2, 2), (2, 0), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (3, 3), (0, 0), (2, 2), (0, 0), (3, 0), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (1, 0), (2, 2), (0, 0), (0, 2), (2, 2), (2, 2), (0, 0), (3, 3), (0, 0), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (0, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (3, 3), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (3, 0), (2, 2), (0, 0), (3, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (3, 0), (2, 2), (0, 0), (2, 2), (0, 0),

In [31]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ',)
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)


[[ 60   0  11   0]
 [  9   3   0   0]
 [  5   0 180   0]
 [  4   0   0   5]]
classification report: 
              precision    recall  f1-score   support

           0       0.77      0.85      0.81        71
           1       1.00      0.25      0.40        12
           2       0.94      0.97      0.96       185
           3       1.00      0.56      0.71         9

    accuracy                           0.90       277
   macro avg       0.93      0.66      0.72       277
weighted avg       0.90      0.90      0.89       277

accuracy of the model:  0.8953068592057761


In [32]:
##predicting using the KNeighbors_classifier
from sklearn.neighbors import KNeighborsClassifier
model_KNN=KNeighborsClassifier(n_neighbors=33,
                               metric='euclidean')

#euclidean,manhattan,min kowski
#fit the model in the data and predict the values

model_KNN.fit(x_train,y_train)
y_pred=model_KNN.predict(x_test)
print(list(zip(y_test,y_pred)))

[(2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (1, 0), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 2), (1, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (3, 3), (0, 0), (2, 2), (0, 2), (3, 0), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (2, 2), (0, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (1, 2), (2, 2), (0, 2), (0, 2), (2, 2), (2, 2), (0, 2), (3, 3), (0, 0), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (0, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 2), (3, 3), (2, 2), (2, 2), (0, 2), (0, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 2), (3, 0), (2, 2), (0, 0), (3, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (3, 0), (2, 2), (0, 0), (2, 2), (0, 0),

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ',)
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)


[[ 32   0  39   0]
 [  5   0   7   0]
 [  1   0 184   0]
 [  5   0   1   3]]
classification report: 
              precision    recall  f1-score   support

           0       0.74      0.45      0.56        71
           1       0.00      0.00      0.00        12
           2       0.80      0.99      0.88       185
           3       1.00      0.33      0.50         9

    accuracy                           0.79       277
   macro avg       0.64      0.44      0.49       277
weighted avg       0.76      0.79      0.75       277

accuracy of the model:  0.7906137184115524


# LOGISTIC 

In [34]:
from sklearn.linear_model import LogisticRegression
#create a model
classifier=LogisticRegression()
#fitting training data into the model
classifier.fit(x_train,y_train)
y_pred=classifier.predict(x_test)
print(y_pred)
print(list(zip(y_test,y_pred)))

[2 2 2 2 2 0 2 2 2 0 0 2 0 2 2 2 2 2 0 2 2 2 2 0 2 2 2 2 3 0 2 2 2 0 2 2 2
 2 2 2 2 2 0 2 0 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 0 3
 2 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 0 2 2 2 2 2
 0 2 0 0 2 2 2 2 2 2 2 2 2 0 2 2 0 2 2 0 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 0 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 0 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 0 2 0 2 2 2 0 2 2 0 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 0 0 2 2 0 2 2 2 2 2 2 2 0 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 3 2 2 2 2 2 2 2 2 2 2 0 2 2 2 2 2]
[(2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 0), (0, 2), (2, 2), (2, 2), (1, 0), (0, 0), (2, 2), (2, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 0), (0, 2), (0, 2), (2, 2), (2, 2), (2, 0), (2, 2), (2, 2), (2, 2), (2, 2), (0, 3), (2, 0), (0, 2), (1, 2), (2, 2), (2, 0), (2, 2), (0, 2), (2, 2), (2, 2), (0, 2), (2, 2), (2, 2), (2, 2), (2, 0), (2, 2), (3, 0), (0, 2), (2, 2), (0, 2), (3, 0), (0, 2), (2, 2), (0, 2), (2, 2), (2, 2), (2, 

In [35]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ',)
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[ 11   0  58   2]
 [  2   0  10   0]
 [ 18   0 167   0]
 [  6   0   2   1]]
classification report: 
              precision    recall  f1-score   support

           0       0.30      0.15      0.20        71
           1       0.00      0.00      0.00        12
           2       0.70      0.90      0.79       185
           3       0.33      0.11      0.17         9

    accuracy                           0.65       277
   macro avg       0.33      0.29      0.29       277
weighted avg       0.56      0.65      0.59       277

accuracy of the model:  0.6462093862815884


# TEST PRED

In [36]:
test=test_data.values
test=scaler.transform(test)

In [37]:
from sklearn.tree import DecisionTreeClassifier

model_DecisionTree=DecisionTreeClassifier(criterion='gini',random_state=10,)

#fit the model on data and predict the values

model_DecisionTree.fit(x_train,y_train)





DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=10, splitter='best')

In [38]:
test_pred=model_DecisionTree.predict(test)
test_pred

array([2, 2, 2, 2, 1, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3,
       2, 0, 2, 2, 2, 2, 2, 0, 1, 3, 1, 2, 0, 2, 0, 2, 2, 2, 2, 3, 2, 2,
       0, 0, 2, 2, 3, 2, 2, 2, 1, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 2, 3, 2, 2, 0, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 3, 2, 2,
       2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 0, 2, 1, 0, 2, 2, 2, 2, 2, 3, 0, 0,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 3, 0, 2, 2, 2, 3, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 2, 0,
       2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2,
       2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 0, 2, 2, 0, 3, 3, 0, 2,
       0, 2, 2, 2, 3, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2,

In [39]:
test_data=pd.read_csv(r'C:\Users\LENOVO\Downloads\cars_test.csv',header=None)
test_data.columns=['BUYING','MAINT','DOORS','PERSONS','LUG_BOOT','SAFETY','CLASESS']
test_data['Pred']=test_pred
test_data['Pred']=test_data['Pred'].map({0:'acc',1:'good',2:'unacc',3:'vgood'})
test_data.head()

BUYING  MAINT  DOORS PERSONS LUG_BOOT SAFETY CLASESS   Pred
0    med  vhigh  5more       4    small    low   unacc  unacc
1  vhigh   high      2       2      big    med   unacc  unacc
2    low   high      2    more    small    low   unacc  unacc
3  vhigh  vhigh      3       2      big   high   unacc  unacc
4    low    med      4       4      med    med    good   good

In [40]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(test_data.CLASESS,test_data.Pred)
print(cfm)

print('classification report: ',)
print(classification_report(test_data.CLASESS,test_data.Pred))

acc=accuracy_score(test_data.CLASESS,test_data.Pred)
print('accuracy of the model: ',acc)

[[ 60   1   3   0]
 [  3  10   0   0]
 [  0   0 251   0]
 [  0   0   0  18]]
classification report: 
              precision    recall  f1-score   support

         acc       0.95      0.94      0.94        64
        good       0.91      0.77      0.83        13
       unacc       0.99      1.00      0.99       251
       vgood       1.00      1.00      1.00        18

    accuracy                           0.98       346
   macro avg       0.96      0.93      0.94       346
weighted avg       0.98      0.98      0.98       346

accuracy of the model:  0.9797687861271677


In [41]:
test_data.to_excel('decision treeoutput.xlsx',header=True)

# BAGGING TECHNIQUES

# RANDOM FOREST

In [42]:
#predicting using random forest classifier
from sklearn.ensemble import RandomForestClassifier

model_RandomForest=RandomForestClassifier(n_estimators=100, random_state=10)

##fit the model in the data and predict the values

model_RandomForest.fit(x_train,y_train)

y_pred=model_RandomForest.predict(x_test)

In [43]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ',)
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[ 65   1   5   0]
 [  4   8   0   0]
 [  1   0 184   0]
 [  0   0   0   9]]
classification report: 
              precision    recall  f1-score   support

           0       0.93      0.92      0.92        71
           1       0.89      0.67      0.76        12
           2       0.97      0.99      0.98       185
           3       1.00      1.00      1.00         9

    accuracy                           0.96       277
   macro avg       0.95      0.89      0.92       277
weighted avg       0.96      0.96      0.96       277

accuracy of the model:  0.9602888086642599


# EXTRA TREES CLASSIFIER

In [44]:
#predicting using random forest classifier
from sklearn.ensemble import ExtraTreesClassifier

model_ExtraTrees=ExtraTreesClassifier(n_estimators=200, random_state=10)

##fit the model in the data and predict the values

model_ExtraTrees.fit(x_train,y_train)

y_pred=model_ExtraTrees.predict(x_test)

In [45]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ',)
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[ 64   0   7   0]
 [  7   5   0   0]
 [  0   0 185   0]
 [  2   0   0   7]]
classification report: 
              precision    recall  f1-score   support

           0       0.88      0.90      0.89        71
           1       1.00      0.42      0.59        12
           2       0.96      1.00      0.98       185
           3       1.00      0.78      0.88         9

    accuracy                           0.94       277
   macro avg       0.96      0.77      0.83       277
weighted avg       0.94      0.94      0.94       277

accuracy of the model:  0.9422382671480144


# USING ADABOOST CLASSIFIER

In [47]:
#predicting using ada_boostclassifier
from sklearn.ensemble import AdaBoostClassifier

model_AdaBoost=AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state=10),
                                  n_estimators=100,random_state=10)

##fit the model in the data and predict the values

model_AdaBoost.fit(x_train,y_train)

y_pred=model_AdaBoost.predict(x_test)

In [48]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ',)
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[ 69   1   1   0]
 [  4   8   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
classification report: 
              precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       0.89      0.67      0.76        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.91      0.93       277
weighted avg       0.98      0.98      0.98       277

accuracy of the model:  0.9783393501805054


# USING GRADIENT BOOSTING CLASSIFIER

In [50]:
#predicting using ada_boostclassifier
from sklearn.ensemble import GradientBoostingClassifier

model_GradientBoosting=GradientBoostingClassifier(n_estimators=100,random_state=10)

##fit the model in the data and predict the values

model_GradientBoosting.fit(x_train,y_train)

y_pred=model_GradientBoosting.predict(x_test)

In [51]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ',)
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[ 70   1   0   0]
 [  3   7   0   2]
 [  1   0 184   0]
 [  0   0   0   9]]
classification report: 
              precision    recall  f1-score   support

           0       0.95      0.99      0.97        71
           1       0.88      0.58      0.70        12
           2       1.00      0.99      1.00       185
           3       0.82      1.00      0.90         9

    accuracy                           0.97       277
   macro avg       0.91      0.89      0.89       277
weighted avg       0.97      0.97      0.97       277

accuracy of the model:  0.9747292418772563


In [52]:
! pip install xgboost

# USING XG BOOST

In [54]:
from xgboost import XGBClassifier

model_xgb=XGBClassifier(n_estimators=100,random_state=10)

##fit the model in the data and predict the values

model_xgb.fit(x_train,y_train)

y_pred=model_xgb.predict(x_test)

[11:43:06] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [55]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ',)
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[ 69   1   1   0]
 [  3   9   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
classification report: 
              precision    recall  f1-score   support

           0       0.96      0.97      0.97        71
           1       0.90      0.75      0.82        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.93      0.95       277
weighted avg       0.98      0.98      0.98       277

accuracy of the model:  0.9819494584837545


# USING VOTING CLASSIFIERS

In [60]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier

# create the sub models
estimators = []
#model1 = LogisticRegression()
#estimators.append(('log', model1))
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
estimators.append(('cart', model2))
model3 = SVC(kernel="rbf", C=90,gamma=0.1)
estimators.append(('svm', model3))
model4 = KNeighborsClassifier(n_neighbors=5, metric='euclidean')
estimators.append(('knn', model4))

In [61]:
# create the ensemble model
ensemble = VotingClassifier(estimators)
ensemble.fit(x_train,y_train)
y_pred=ensemble.predict(x_test)
#print(Y_pred)



In [62]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

cfm=confusion_matrix(y_test,y_pred)
print(cfm)

print('classification report: ',)
print(classification_report(y_test,y_pred))

acc=accuracy_score(y_test,y_pred)
print('accuracy of the model: ',acc)

[[ 69   0   2   0]
 [  4   8   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
classification report: 
              precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       1.00      0.67      0.80        12
           2       0.99      1.00      0.99       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.98      0.91      0.94       277
weighted avg       0.98      0.98      0.98       277

accuracy of the model:  0.9783393501805054
